In [55]:
import pandas as pd
import numpy as np

In [2]:
af= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')
af

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

### Renaming The Columns

In [3]:
# Renaming the columns 
# Syntax:
 # var = {'old_col': 'new_col'}
#var1.rename (columns=var,inplace=True)

In [4]:
af.info()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   str
 2   estado    6454 non-null   str
 3   numero    6322 non-null   str
 4   encontro  6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 413.0 KB

In [5]:
af.head(5)

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [6]:
d={'ano':'year','mes':'months'}
af.rename(columns=d,inplace=True)

In [7]:
d= {'estado':'states','numero':'fire_No','encontro':'date'}
af.rename(columns=d,inplace=True)

In [8]:
af.head()

   year   months states  fire_No      date
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [9]:
tips =pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [10]:
a={'sex':'gender'}
tips.rename(columns=a,inplace =True)

In [11]:
tips

     Unnamed: 0  total_bill   tip  gender smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [12]:
hr = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [32]:

hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

### Remove Duplicates

In [13]:
# Removing duplicates rows:
# syntax:
#         var.drop_duplicates(inplace=True)

In [51]:
df= pd.DataFrame(
  {
      'Ename':['veivek','veivek','kushi','sumit','chuccu',np.nan,np.nan],
      'Eno':[102,102,np.nan,105,106,104,np.nan],
      'Sal':['10LPA','10LPA',np.nan,np.nan,np.nan,'10LPA',np.nan]
      
  }
)
df

    Ename    Eno    Sal
0  veivek  102.0  10LPA
1  veivek  102.0  10LPA
2   kushi    NaN    NaN
3   sumit  105.0    NaN
4  chuccu  106.0    NaN
5     NaN  104.0  10LPA
6     NaN    NaN    NaN

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.dropna(inplace=True)

In [17]:
df

    Ename    Eno    Sal
0  veivek  102.0  10LPA

### Changing the data present in column

In [18]:
# Syntax:
# var={'old_data':'new_data'}
# var1['col_name']=var1['col_name'].map(var)

In [19]:
af.head(2)

   year   months states  fire_No      date
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999

In [20]:
af_data= {'Janeiro':'Jan','Dezembro':'Dec'}
af['months']=af['months'].map(af_data)

In [21]:
af

      year months     states  fire_No      date
0     1998    Jan       Acre  0 Fires  1/1/1998
1     1999    Jan       Acre  0 Fires  1/1/1999
2     2000    Jan       Acre  0 Fires  1/1/2000
3     2001    Jan       Acre  0 Fires  1/1/2001
4     2002    Jan       Acre  0 Fires  1/1/2002
...    ...    ...        ...      ...       ...
6449  2012    Dec  Tocantins      128  1/1/2012
6450  2013    Dec  Tocantins       85  1/1/2013
6451  2014    Dec  Tocantins      223  1/1/2014
6452  2015    Dec  Tocantins      373  1/1/2015
6453  2016    Dec  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [22]:
af['months'].unique()

<ArrowStringArray>
['Jan', nan, 'Dec']
Length: 3, dtype: str

In [23]:
### Removing Unwanted Data present in the columns
# Syntax:
#         var['col-name']=var['col_name'].str.strip('unwanted_data')

In [24]:
af['fire_No']= af['fire_No'].str.strip('unwanted_data')

In [25]:
af

      year months     states  fire_No      date
0     1998    Jan       Acre  0 Fires  1/1/1998
1     1999    Jan       Acre  0 Fires  1/1/1999
2     2000    Jan       Acre  0 Fires  1/1/2000
3     2001    Jan       Acre  0 Fires  1/1/2001
4     2002    Jan       Acre  0 Fires  1/1/2002
...    ...    ...        ...      ...       ...
6449  2012    Dec  Tocantins      128  1/1/2012
6450  2013    Dec  Tocantins       85  1/1/2013
6451  2014    Dec  Tocantins      223  1/1/2014
6452  2015    Dec  Tocantins      373  1/1/2015
6453  2016    Dec  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [26]:
af['months']= af['months'].str.upper()

In [27]:
af

      year months     states  fire_No      date
0     1998    JAN       Acre  0 Fires  1/1/1998
1     1999    JAN       Acre  0 Fires  1/1/1999
2     2000    JAN       Acre  0 Fires  1/1/2000
3     2001    JAN       Acre  0 Fires  1/1/2001
4     2002    JAN       Acre  0 Fires  1/1/2002
...    ...    ...        ...      ...       ...
6449  2012    DEC  Tocantins      128  1/1/2012
6450  2013    DEC  Tocantins       85  1/1/2013
6451  2014    DEC  Tocantins      223  1/1/2014
6452  2015    DEC  Tocantins      373  1/1/2015
6453  2016    DEC  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

### handing with NaN value

In [30]:
### deleteing NaN value 
hr.dropna(inplace=True)

In [31]:
hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [33]:
hr.info()

<class 'pandas.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  str
 8   salary                 14999 non-null  str
dtypes: int64(7), str(2)
memory usage: 1.2 MB

In [36]:
df

    Ename    Eno    Sal
0  veivek  102.0  10LPA
1  veivek  102.0  10LPA
2   kushi    NaN    NaN
3   sumit  105.0    NaN
4  chuccu  106.0    NaN
5     NaN  104.0  10LPA
6     NaN    NaN    NaN

In [37]:
### Filling NaN Value
# Syntax: var['col_name']= var['col_name'].fillna(value)

In [95]:
df= pd.DataFrame(
  {
      'Ename':['veivek','veivek','kushi','sumit','chuccu',np.nan,np.nan],
      'Eno':[102,102,np.nan,105,106,104,np.nan],
      'Sal':['6LPA','5LPA',np.nan,np.nan,np.nan,'15LPA',np.nan]
      
  }
)
df

    Ename    Eno    Sal
0  veivek  102.0   6LPA
1  veivek  102.0   5LPA
2   kushi    NaN    NaN
3   sumit  105.0    NaN
4  chuccu  106.0    NaN
5     NaN  104.0  15LPA
6     NaN    NaN    NaN

In [96]:
df['PF']=[100,200,2200,np.nan,500,744,np.nan]
df

    Ename    Eno    Sal      PF
0  veivek  102.0   6LPA   100.0
1  veivek  102.0   5LPA   200.0
2   kushi    NaN    NaN  2200.0
3   sumit  105.0    NaN     NaN
4  chuccu  106.0    NaN   500.0
5     NaN  104.0  15LPA   744.0
6     NaN    NaN    NaN     NaN

In [104]:
d= round(df['PF'].mean())

In [105]:
df['PF']= df['PF'].fillna(d)

In [86]:
df

    Ename    Eno    Sal      PF
0  veivek  102.0   6LPA   100.0
1  veivek  102.0   5LPA   200.0
2   kushi    NaN    NaN  2200.0
3   sumit  105.0    NaN   749.0
4  chuccu  106.0    NaN   500.0
5     NaN  104.0  15LPA   744.0
6     NaN    NaN    NaN   749.0

In [87]:
df['Eno']= df['Eno'].fillna('Terminated')

In [88]:
df

    Ename         Eno    Sal      PF
0  veivek       102.0   6LPA   100.0
1  veivek       102.0   5LPA   200.0
2   kushi  Terminated    NaN  2200.0
3   sumit       105.0    NaN   749.0
4  chuccu       106.0    NaN   500.0
5     NaN       104.0  15LPA   744.0
6     NaN  Terminated    NaN   749.0

In [89]:
##  Forward filling and backward filling 
# Forword filling
# Syntax:
# var['col_name']= var['col_name'].ffill()

In [90]:
df['Sal']=df['Sal'].ffill()

In [94]:
df

    Ename         Eno    Sal      PF
0  veivek       102.0   6LPA   100.0
1  veivek       102.0   5LPA   200.0
2   kushi  Terminated   5LPA  2200.0
3   sumit       105.0   5LPA   749.0
4  chuccu       106.0   5LPA   500.0
5     NaN       104.0  15LPA   744.0
6     NaN  Terminated  15LPA   749.0

In [97]:
##  Forward filling and backward filling 
# Backward filling
# Syntax:
# var['col_name']= var['col_name'].bfill()

In [98]:
df

    Ename    Eno    Sal      PF
0  veivek  102.0   6LPA   100.0
1  veivek  102.0   5LPA   200.0
2   kushi    NaN    NaN  2200.0
3   sumit  105.0    NaN     NaN
4  chuccu  106.0    NaN   500.0
5     NaN  104.0  15LPA   744.0
6     NaN    NaN    NaN     NaN

In [99]:
df['Sal']= df['Sal'].bfill()

In [100]:
df['PF']= df['PF'].fillna()

    Ename    Eno    Sal      PF
0  veivek  102.0   6LPA   100.0
1  veivek  102.0   5LPA   200.0
2   kushi    NaN  15LPA  2200.0
3   sumit  105.0  15LPA     NaN
4  chuccu  106.0  15LPA   500.0
5     NaN  104.0  15LPA   744.0
6     NaN    NaN    NaN     NaN

df.info()

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ename   5 non-null      str
 1   Eno     5 non-null      float64
 2   Sal     6 non-null      str
 3   PF      7 non-null      float64
dtypes: float64(2), str(2)
memory usage: 414.0 bytes

In [101]:
# var['col_nmae']=var['Col_name'].astype(data_type)

In [111]:
df['PF']= df['PF'].astype('int')

In [112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Ename   5 non-null      str
 1   Eno     5 non-null      float64
 2   Sal     6 non-null      str
 3   PF      7 non-null      int64
dtypes: float64(1), int64(1), str(2)
memory usage: 414.0 bytes

In [114]:
af.info()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     6454 non-null   int64
 1   months   1054 non-null   str
 2   states   6454 non-null   str
 3   fire_No  6322 non-null   str
 4   date     6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 376.0 KB

In [118]:
af['fire_No'].unique()

<ArrowStringArray>
[ '0 Fires', '10 Fires', '12 Fires',  '4 Fires',  '1 Fires',  '3 Fires',
  '5 Fires',  '2 Fires', '11 Fires',        nan,
 ...
    '2.913',      '718',    '2.272',    '1.591',     '3.68',    '2.155',
    '4.844',    '2.032',      '833',      '623']
Length: 1729, dtype: str

In [119]:
af['fire_No']=af['fire_No'].str.strip('Fires')

In [121]:
af.info()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     6454 non-null   int64
 1   months   1054 non-null   str
 2   states   6454 non-null   str
 3   fire_No  6322 non-null   str
 4   date     6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 371.4 KB

In [123]:
af.isnull().sum()

year          0
months     5400
states        0
fire_No     132
date          0
dtype: int64

In [126]:
af['fire_No']=af['fire_No'].astype('float')

In [128]:
fire_no_avg= round(af['fire_No'].mean())

In [129]:
af['fire_No']= af['fire_No'].fillna(fire_no_avg)

In [130]:
af['fire_No']=af['fire_No'].astype('int')

In [131]:
af.info()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     6454 non-null   int64
 1   months   1054 non-null   str
 2   states   6454 non-null   str
 3   fire_No  6454 non-null   int64
 4   date     6454 non-null   str
dtypes: int64(2), str(3)
memory usage: 354.9 KB

In [133]:
af['fire_No'].unique()

array([  0,  10,  12,   4,   1,   3,   5,   2,  11, 111,  19,   7,   6,
         8,   9,  21,  27,  17,  40,  87,  45,  37,  39, 168,  42,  33,
        29,  41,  31, 126,  93,  71,  54,  60, 109, 533, 457, 130,  63,
       136, 396, 728, 645, 839, 960, 445, 194, 425, 739, 679, 509, 209,
       265, 290,  44,  18, 137, 687, 740, 461, 547, 316, 203, 652, 565,
       292,  97, 348, 258, 406, 905,  86,  15,  14,  74,  13,  79,  56,
        46,  98,  58, 150,  83,  55, 104,  23,  36,  49,  81,  24,  38,
        20,  16,  28,  32,  26,  52,  35,  70,  34,  25,  22,  30,  95,
       162,  76,  43,  50,  59, 155,  73,  88,  67, 112,  61, 128,  85,
       192, 142, 557, 355, 412, 335, 405, 395, 765, 304, 475, 385, 480,
       827, 793, 131, 157, 750, 949, 685, 207, 198, 266, 339, 282, 969,
       341, 484, 858,  84, 593, 200, 411, 123, 360, 422, 148, 354, 269,
       491, 158,  82,  53, 770,  65,  62,  92, 107, 275,  69,  64, 116,
       140,  51,  78,  90, 119, 146, 180, 177, 676, 108, 199, 640, 271,
       234, 248, 202, 356, 321, 259, 501, 741, 861, 267, 216, 189, 166,
       928, 911, 998, 479, 145, 332, 695, 725, 710, 545, 721, 215, 632,
       889, 694, 952, 244, 169, 261, 973, 399, 682, 220, 591, 552, 196,
       147, 102, 121,  80, 236, 293, 133, 114, 125, 439, 303, 225, 373,
       314, 297, 101, 179, 132, 256, 285, 154, 204, 223, 122, 143, 277,
       113, 235, 117, 206, 156, 231, 418, 100, 274, 115, 141, 135, 249,
       404, 363, 229, 281, 163, 110, 376,  89, 151, 103, 149, 183, 190,
        94, 106, 124, 120, 161, 326, 224, 144, 178, 118, 289, 211,  68,
       270,  72, 345, 208, 243, 242, 416, 329, 219, 310, 811, 519, 578,
       906, 362, 300, 815, 453, 633, 979, 948, 995, 611, 610, 674, 829,
       724, 699, 239, 402, 605, 288, 408, 174, 848, 423, 308, 226, 230,
       477, 164,  47, 264, 384, 347, 273,  91,  75, 182, 278, 127, 590,
       801, 172, 185, 237, 241, 357, 609, 214, 370, 505, 309, 875, 581,
       964, 816, 435, 502, 415, 466, 517, 658, 575, 524, 669, 812, 276,
       397, 389, 631, 956, 643, 819,  48, 159,  99,  66,  96, 152,  77,
       105, 134, 186, 245, 246, 184, 173, 139, 263, 232, 318, 407, 625,
       467, 336, 446, 707, 462, 559, 769, 959, 901, 528, 616, 417, 914,
       892, 153, 398, 295,  57, 702, 391, 759, 511, 175, 459, 379, 713,
       755, 530, 617, 233, 450, 188, 644, 626, 704, 197, 252, 279, 129,
       436, 221, 428, 319, 195, 494, 187, 286, 338, 706, 529, 515, 602,
       915, 498, 887, 709, 885, 549, 512, 972, 895, 800, 896, 301, 438,
       947, 476, 527, 298, 171, 315, 374, 482, 592, 272, 871, 383, 213,
       431, 193, 375, 542, 337, 554, 743, 448, 325, 563, 655, 705, 719,
       641, 903, 441, 372, 521, 859, 606, 731, 942, 359, 516, 933, 541,
       845, 856, 403, 974, 842, 299, 588, 768, 918, 813, 846, 492, 447,
       201, 165, 170, 291, 328, 927, 394, 160, 935, 589, 250, 538, 371,
       228, 953, 456, 677, 510, 365, 576, 657, 647, 668, 432, 854, 597,
       378, 507, 306, 380, 577, 579, 437, 392, 167, 251, 430, 181, 340,
       638, 426, 708, 772, 615, 971, 661, 825, 766, 689, 684, 381, 294,
       238, 331, 280, 451, 351, 262, 504, 891, 938, 849, 342, 844, 580,
       733, 522, 481, 646, 651, 987, 878, 386, 866, 413, 913, 443, 599,
       452, 666, 327, 424, 503, 388, 138, 254, 560, 465, 486, 831, 352,
       191, 364, 176, 334, 834, 283, 534, 564, 919, 302, 864, 361, 690,
       754, 711, 499, 943, 790, 872, 939, 594, 717, 897, 449, 788, 317,
       570, 468, 346, 205, 353, 313, 500, 366, 212, 222, 284, 865, 824,
       642, 410, 414, 828, 444, 573, 628, 343, 680, 227, 539, 798, 747,
       483, 796, 822, 555, 526, 253, 401, 217, 330, 767, 820, 665, 268,
       312, 307, 562, 210, 596, 600, 802, 595, 934, 794, 572, 470, 497,
       797, 981, 525, 582, 977, 809, 495, 882, 368, 490, 434, 763, 260,
       488, 419, 369, 350, 618, 778, 305, 421, 922, 873, 830, 976, 762,
       982, 989, 718, 833, 623])

In [134]:
## Rearranging the orderof Columns
# new_order =[0,2,4,3]
#var= var[var.columns[new_order]]

In [135]:
df

    Ename    Eno    Sal    PF
0  veivek  102.0   6LPA   100
1  veivek  102.0   5LPA   200
2   kushi    NaN  15LPA  2200
3   sumit  105.0  15LPA   749
4  chuccu  106.0  15LPA   500
5     NaN  104.0  15LPA   744
6     NaN    NaN    NaN   749

In [139]:
list= [3,2,1,0]
df=df[df.columns[list]]
df

    Ename    Sal    Eno    PF
0  veivek   6LPA  102.0   100
1  veivek   5LPA  102.0   200
2   kushi  15LPA    NaN  2200
3   sumit  15LPA  105.0   749
4  chuccu  15LPA  106.0   500
5     NaN  15LPA  104.0   744
6     NaN    NaN    NaN   749

In [140]:
### Droping unwanted  Columns from dataFrame
# var = var.drop([col_1,col_2,...,col_N],axis=1)

In [141]:
df= df.drop(['PF'],axis=1)

In [142]:
df

    Ename    Sal    Eno
0  veivek   6LPA  102.0
1  veivek   5LPA  102.0
2   kushi  15LPA    NaN
3   sumit  15LPA  105.0
4  chuccu  15LPA  106.0
5     NaN  15LPA  104.0
6     NaN    NaN    NaN

In [158]:
df['PF']=[100,200,5,2000,100,122]

In [159]:
df

    Ename    Sal    Eno    PF
0  veivek   6LPA  102.0   100
1  veivek   5LPA  102.0   200
2   kushi  15LPA    NaN     5
3   sumit  15LPA  105.0  2000
5     NaN  15LPA  104.0   100
6     NaN    NaN    NaN   122

In [161]:
### Droping Unwanted Data from Rows
# var = var.drop(var.index[index_number])
# var = var.drop(var.index[[index_1,index_2,...........,index_N]])
df

    Ename    Sal    Eno
0  veivek   6LPA  102.0
1  veivek   5LPA  102.0
2   kushi  15LPA    NaN
3   sumit  15LPA  105.0
5     NaN  15LPA  104.0
6     NaN    NaN    NaN

In [162]:
#### Changing the particular Data from the DataFrame

### var['col_name']=var['col_name'].str.replace('old_data','new_data')

In [163]:
df['Ename']= df['Ename'].str.replace('veivek','Vivek')

In [164]:
df

   Ename    Sal    Eno
0  Vivek   6LPA  102.0
1  Vivek   5LPA  102.0
2  kushi  15LPA    NaN
3  sumit  15LPA  105.0
5    NaN  15LPA  104.0
6    NaN    NaN    NaN

In [172]:
af['months']= af['months'].str.replace('JAN','January')
af['months']= af['months'].str.replace('DEC','December')

In [173]:
af

      year    months     states  fire_No      date      sates
0     1998   January       Acre        0  1/1/1998       Acre
1     1999   January       Acre        0  1/1/1999       Acre
2     2000   January       Acre        0  1/1/2000       Acre
3     2001   January       Acre        0  1/1/2001       Acre
4     2002   January       Acre        0  1/1/2002       Acre
...    ...       ...        ...      ...       ...        ...
6449  2012  December  Tocantins      128  1/1/2012  Tocantins
6450  2013  December  Tocantins       85  1/1/2013  Tocantins
6451  2014  December  Tocantins      223  1/1/2014  Tocantins
6452  2015  December  Tocantins      373  1/1/2015  Tocantins
6453  2016  December  Tocantins      119  1/1/2016  Tocantins

[6454 rows x 6 columns]