In [2]:
import pandas as pd

In [11]:
hr = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [12]:
hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [ ]:
## GroupBy  : group by is used when we want to split the data into group based on column
##  syntax : var = var1.groupby('categorical_column')
##            var.groups
###            var.get_group('group_name')

In [19]:
dept= hr.groupby('department')
dept.groups
dept.get_group('sales')

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14967,87507,2,128,3,0,1,0,sales,low
14968,87518,2,128,3,0,1,0,sales,medium
14969,87520,2,157,3,0,1,0,sales,medium
14970,87530,4,225,5,0,1,0,sales,medium
14971,87533,2,140,3,0,1,0,sales,medium

In [20]:

hr['salary'].unique()

<ArrowStringArray>
['low', 'medium', 'high']
Length: 3, dtype: str

In [21]:
salary= hr.groupby('salary')
salary.get_group('low')

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
5,1060,2,153,3,0,1,0,sales,low
6,1061,6,247,4,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [23]:
titnic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv')

In [24]:
titnic

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [40]:
titnic['embarked'].unique()

<ArrowStringArray>
['S', 'C', nan, 'Q']
Length: 4, dtype: str

In [44]:
titnic.dropna(inplace=True)

In [45]:
titnic['embarked'].unique()

<ArrowStringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [46]:
tia= titnic.groupby('embarked')
tia.get_group('S')

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1188,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...",female,24.0000,0,2,PP 9549,16.7000,G6,S,1
1189,3,"Sandstrom, Miss. Marguerite Rut",female,4.0000,1,1,PP 9549,16.7000,G6,S,1
1217,3,"Soholt, Mr. Peter Andreas Lauritz Andersen",male,19.0000,0,0,348124,7.6500,F G73,S,0
1230,3,"Strom, Miss. Telma Matilda",female,2.0000,0,1,347054,10.4625,G6,S,0
1231,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.0000,1,1,347054,10.4625,G6,S,0

In [ ]:
### Groupby multiple value 
## var1 = var.groupby(['col1','col2'])
## var1.groups
# var1.get_group((val1,val2))

In [48]:
hrs= hr.groupby(['department','salary'])
hrs.groups
hrs.get_group(('sales','high'))

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
696,4979,7,291,4,0,1,0,sales,high
774,5398,2,152,3,0,1,0,sales,high
852,5884,5,217,5,0,1,0,sales,high
930,6370,5,271,5,0,1,0,sales,high
1008,6835,4,256,5,0,1,0,sales,high
...,...,...,...,...,...,...,...,...,...
13929,81338,4,182,3,1,0,0,sales,high
13940,8304,5,231,7,0,0,1,sales,high
13944,8848,5,160,3,1,0,0,sales,high
13948,11277,3,215,6,0,0,0,sales,high
14121,82500,4,211,7,0,0,0,sales,high

In [49]:
### Data Aggrigation:
###  1) sum():- It will  return the sum of all values
###   2) mean():- It will return average values
###  3) meadian():- It 
###  4) mode():- most occarant value
###  5) count():- count of not null  values
###  6) min(): it will return  minumn value
###  7) max(): it will return maximum value

In [52]:
hr['time_spend_company'].max()

10

In [58]:
## find the number of employee who left the company
hr[hr['left']==1]['left'].count()

np.int64(3571)

In [54]:
hr['left'].unique()

array([1, 0])

In [62]:
hr[hr['salary']=='low']['salary'].count()

np.int64(7316)

In [64]:
hres=hr.groupby('salary')
hres.get_group('low')['salary'].count()

np.int64(7316)

In [70]:
## no of employee in sales deptarment
hr.groupby('department')['department'].count()

department
IT             1227
RandD           787
accounting      767
hr              739
management      630
marketing       858
product_mng     902
sales          4140
support        2229
technical      2720
Name: department, dtype: int64