## Pandas

 Features of Pandas 
1) Import Datasets.
2) data cleaning.
3) Size Mutability.
4) Reshaping & pivoting  of Datasets.
5) Efficient manuplation and extraction.
6) Analysis.

In [8]:
import pandas as pd
import numpy as np

1) Series
2) Dataframes

#### Series

In [9]:
# creating series
# Syntax :- pd.Series([value1,value2,value3,......value n])
data = pd.Series([True,2,5,6,3,77],name='values')
data

0    True
1       2
2       5
3       6
4       3
5      77
Name: values, dtype: object

In [10]:

d= [51,251,254,225,254,254,124]
val_2= pd.Series(d,name='value',index=['Math','Java','kalu','m2','alu','kal','malu'])

In [11]:
val_2

Math     51
Java    251
kalu    254
m2      225
alu     254
kal     254
malu    124
Name: value, dtype: int64

In [12]:
c={
    'a':25,
    'n':True,
     'm':25
}

In [13]:
d_1= pd.Series(c, name="kalu")

In [14]:
d_1

a      25
n    True
m      25
Name: kalu, dtype: object

In [15]:
 array = np.arange(1,4)

In [16]:
array

array([1, 2, 3])

In [17]:
array_1 = pd.Series(array,name='array',index=['a','b','c'])
array_1

a    1
b    2
c    3
Name: array, dtype: int64

In [18]:
T =('jadu','kalu','lambu','MC')
List=['k','sl','sdcs','safaf']

In [19]:
Tuple_1= pd.Series( T,name='Tuple')
Tuple_1

0     jadu
1     kalu
2    lambu
3       MC
Name: Tuple, dtype: str

##  iloc()   
  #### it is also known as location based indexing.

In [20]:
####  iloc()   
  # it is also known as location based indexing.
# 1) var.iloc[index]
Tuple_1.iloc[2]

'lambu'

In [21]:
# 2) var.iloc[[index_val,index_val,..., index_val]]
# it will use for the find out multiple value
Tuple_1.iloc[[1,2]]

1     kalu
2    lambu
Name: Tuple, dtype: str

In [22]:
Tuple_1.iloc[[]]

Series([], Name: Tuple, dtype: str)

In [23]:
val_2

Math     51
Java    251
kalu    254
m2      225
alu     254
kal     254
malu    124
Name: value, dtype: int64

In [24]:
val_2.iloc[0:5:1]

Math     51
Java    251
kalu    254
m2      225
alu     254
Name: value, dtype: int64

In [25]:
# loc :- Label Based Indexing , it is basically used in the Data Set
#        
# var.loc[[index_val,index_val,..,index]]
Tuple_1

0     jadu
1     kalu
2    lambu
3       MC
Name: Tuple, dtype: str

In [26]:
Tuple_1.loc[0:2:1]

0     jadu
1     kalu
2    lambu
Name: Tuple, dtype: str

Difference between Array And Series 
Array
-> Array belongs to numpy 
-> After string it will consider as object
-> If array it displays only the data 
-> np.array()

Series
-> Series belongs to panda
-> After complex every data type will consider as object
-> it displays data, index,datatype
-> pd.Series()

### DataFrames

In [27]:
# Syntax:- 
     # var = pd.DataFrame(Dictionary)

In [28]:
df= pd.DataFrame(
    {
        'Ename':['Ram','Raju','Karan',"Suraj"],
         'Eid' : [25,26,54,250],
          'sal': ['7L','5L','54L','4L']
    }
)

In [29]:
df

   Ename  Eid  sal
0    Ram   25   7L
1   Raju   26   5L
2  Karan   54  54L
3  Suraj  250   4L

In [30]:

# Operation on Data Frame 
student = pd.DataFrame(
    {
        'Sname':['raju','karan','mohan','konal','Ram','Raju','Karan',"Suraj"],
        'Sid':[14,52,45,12,54,25,65,45],
        'Class':[1,2,3,5,1,5,2,2]
    }
)

In [31]:
student

   Sname  Sid  Class
0   raju   14      1
1  karan   52      2
2  mohan   45      3
3  konal   12      5
4    Ram   54      1
5   Raju   25      5
6  Karan   65      2
7  Suraj   45      2

In [32]:
# Syntax  to access the particular column ,
#                      Syntax:-    var['col_name']

In [33]:
student['Sname']

0     raju
1    karan
2    mohan
3    konal
4      Ram
5     Raju
6    Karan
7    Suraj
Name: Sname, dtype: str

In [34]:
# Syntax to access the multiple column
#               Syntax :-      var[[col_name_1,col_name_2,.....col_name_n]]
student[['Sname','Sid']]

   Sname  Sid
0   raju   14
1  karan   52
2  mohan   45
3  konal   12
4    Ram   54
5   Raju   25
6  Karan   65
7  Suraj   45

In [35]:
#  To access the multiple  vlaue from the dataframe 
# Syntax : 
#                  var[SV:EV+-1,UP]
student[::2]

   Sname  Sid  Class
0   raju   14      1
2  mohan   45      3
4    Ram   54      1
6  Karan   65      2

In [36]:
# To modify the Existing value from the DataFrame
  # Syntax :     var['col_name'][index]=new_value

In [37]:
 student['Sname'][0]='Vivek'

C:\Users\vivek\AppData\Local\Temp\ipykernel_11172\835738534.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  student['Sname'][0]='Vivek'

In [38]:
 #Syntax ;- varirable.loc[row_indexer, col_indexer] = value

In [39]:
student.loc[2,'Sid']=65
student

   Sname  Sid  Class
0   raju   14      1
1  karan   52      2
2  mohan   65      3
3  konal   12      5
4    Ram   54      1
5   Raju   25      5
6  Karan   65      2
7  Suraj   45      2

In [40]:
# Date:- 19-03-2026

In [41]:
# To Add a new column in DataFrame.
# var['new_col_name']= [equal no of value which were present in D.F]

In [42]:
df['Blood Group']= ['A+','O','B-','AB+']

In [43]:
df

   Ename  Eid  sal Blood Group
0    Ram   25   7L          A+
1   Raju   26   5L           O
2  Karan   54  54L          B-
3  Suraj  250   4L         AB+

In [44]:
# to read CSV file 
           # var = pd.read_csv('File_Path')
            # for Unicodedecode Error 
              # we will pass  argument  {  encoding='ISO-8859-1' }

In [73]:
hr = pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [74]:
hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [75]:
tips =pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')
tips

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34  1.66    Male     No   Sun  Dinner     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [76]:
af= pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')
af

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
# var.head(n)    :-  it will display first 5 Row
#                where n is stand for the n of Rows
# var.tail(n)      :- it will display 5 Rows from bottom 
# var.info()         :- it will give the information of the dataset
# var.describe()    :- it will return the statical information  about the data / DataFrame.
#                       it will only work with numerical DataType

In [ ]:
af.head()

In [ ]:
af.tail()

In [ ]:
af.info()

In [ ]:
af.describe()

In [ ]:
hr.describe()

In [ ]:
hr['number_project'].unique()

In [ ]:
hr

In [ ]:
#  var.describe(include=object):-  
#                                 it will return statical information including object data as well as 
#  var.shape                        :- 
#                                 it will return the shape of the data in Row and Columns
af.describe(include=object)

In [ ]:
# var['col_name'].unique()  :-
#                              it will return the unique value form the column of te dataframe
# var['col_name'].value_counts() :-
#                                    it will count how many times a unique value got  selected 
                                    

af['mes'].unique()

In [ ]:
hr.head(2)

In [ ]:
hr['department'].unique()

In [ ]:
# var['col_name'].value_counts() :-
#                                    it will count how many times a unique value got  repeated. 
af['mes'].value_counts()

In [ ]:
# var.columns:-  
#              it will return  the all columns  that are present in data set in array format 
af.columns

In [ ]:
var.sample(n)
#                  it will fetch the random row from the dataframe
#          n  :  it is use to fatch the n number of rows from the DataFrame
af.sample(2)

In [ ]:
# slicing in data sets

In [ ]:
# var.loc[index]:
#                it will returnall the data of columns for mention index.

In [53]:
# var.loc[SV:EV:UP, 'col_name']

In [47]:
df=pd.read_csv('Social_Network_Ads.csv')

In [52]:
df.loc[1:6:]

Empty DataFrame
Columns: [User ID, Gender, Age, EstimatedSalary, Purchased]
Index: []

In [51]:
df.iloc[::-1]

      User ID  Gender  Age  EstimatedSalary  Purchased
399  15594041  Female   49            36000          1
398  15755018    Male   36            33000          0
397  15654296  Female   50            20000          1
396  15706071    Male   51            23000          1
395  15691863  Female   46            41000          1
..        ...     ...  ...              ...        ...
4    15804002    Male   19            76000          0
3    15603246  Female   27            57000          0
2    15668575  Female   26            43000          0
1    15810944    Male   35            20000          0
0    15624510    Male   19            19000          0

[400 rows x 5 columns]

In [56]:
df.loc[1:7:2,['Age','EstimatedSalary']]

   Age  EstimatedSalary
1   35            20000
3   27            57000
5   27            58000
7   32           150000

In [57]:
# iloc:-
# it is used to slice through multiple column and rows
# var.iloc[row_slice,columns slice]

In [58]:
df.iloc[1:8:2,1:4:1]

   Gender  Age  EstimatedSalary
1    Male   35            20000
3  Female   27            57000
5    Male   27            58000
7  Female   32           150000

In [59]:
# Boolean Filttering:
# Syntax :
#           var[condition]
# it will return  in the true and false

In [60]:
titnic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv')

In [61]:
titnic.head(4)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0

In [63]:
titnic[titnic['sex'] == 'male']

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1302,3,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C,0
1303,3,"Yousseff, Mr. Gerious",male,NaN,0,0,2627,14.4583,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [64]:
titnic[titnic['sex']=='female']

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,1
1304,3,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0

In [65]:
titnic[titnic['age']>50]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,0
14,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,1
33,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1068,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S,0
1225,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S,0
1235,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,0
1261,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,1
1287,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S,0

In [67]:
titnic[titnic['age']>50 & (titnic['survived'] == 1)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1301,3,"Youseff, Mr. Gerious",male,45.5000,0,0,2628,7.2250,NaN,C,0
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [71]:
titnic[titnic['pclass']==1 or titnic['pclass']==3]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [81]:
# show the data  dept sales and salary low
hr[(hr['department'] == 'sales') & (hr['salary'] == 'low')]

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
5,1060,2,153,3,0,1,0,sales,low
6,1061,6,247,4,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14963,90813,6,271,4,0,1,0,sales,low
14964,87480,6,280,4,0,1,0,sales,low
14965,87497,2,149,3,0,1,0,sales,low
14966,87500,5,219,5,0,1,0,sales,low
14967,87507,2,128,3,0,1,0,sales,low

In [77]:
hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [82]:
# to show  premostion in last year and time spending in company greater that 4
hr[(hr['promotion_last_5years']==1) & (hr['time_spend_company']> 4)]

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
1000,6792,4,258,5,1,1,1,sales,medium
4541,88646,3,286,6,0,0,1,technical,medium
4552,26968,4,269,5,0,0,1,support,medium
4556,26993,4,163,5,0,0,1,support,low
4735,27931,6,275,5,1,0,1,support,medium
...,...,...,...,...,...,...,...,...,...
14205,83010,3,193,10,0,0,1,management,high
14206,83017,3,259,10,1,0,1,management,high
14207,83019,5,266,10,0,0,1,management,high
14208,83020,3,185,10,0,0,1,management,high
14209,83025,3,172,10,0,0,1,marketing,high

In [83]:
# to shpw the salary is  low and left the company 
hr[(hr['salary']=='low') & (hr['left']==1)]

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
5,1060,2,153,3,0,1,0,sales,low
6,1061,6,247,4,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low




### ISNULL ()

In [84]:
# isnull()
#            it will returns only the null data 
# syntax :- 
#         var[var['col_name'].isnull()]

In [89]:
hr['number_project'].isnull().sum()

np.int64(0)

In [87]:
hr.isnull().sum()

employee_id              0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
department               0
salary                   0
dtype: int64

### notnull()

In [90]:
# notnull():-
# it will return only the non null data 
# syntax:- 
#          var[var['col_name'].notnull()]

In [94]:
hr.notnull().sum()

employee_id              14999
number_project           14999
average_montly_hours     14999
time_spend_company       14999
Work_accident            14999
left                     14999
promotion_last_5years    14999
department               14999
salary                   14999
dtype: int64